<?xml version="1.0" encoding="utf-8"?><Database Name="LGH" Class="DataclassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=rOVAID;Initial Catalog=LGH;Integrated Security=True" SettingsObjectName="LGH.Properties.Settings" SettingsPropertyName="LGHConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Bio_Data_Form" Member="Bio_Data_Forms">
    <Type Name="Bio_Data_Form">
      <Column Name="BDF_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SDW_O" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DOB" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Date_of_Superannuation" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Sex" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Martial_Status" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Next_Of_Kin" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Permanent_Address" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Cnic_No" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cell_No" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Emergency_ContactNo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Landline_PTCL_No" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Passport_No" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Domicile" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PRC" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Personal_No" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Service_Book_No" Type="System.String" DbType="NVarChar(70)" CanBeNull="true" />
      <Column Name="Date_Of_Joinning" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Joinning_at_LGHK" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Joinning_at_LGHK_no" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Posted_at_LGHK_On" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status_Before_Joinning_LGHK" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Posted_at_LGHK_In" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="lghk_vacantpost" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Designation" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="Cadre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BPS" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Service_Type" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Service_Type_Datetime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PM_DC#" Member="PM_DC_" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Qualification" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Any_Other_Qualification" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Last_Institute" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Date_Last_Promotion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Promoted_BPS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DOL_Ex_Pak_Leave" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Dated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Remarks" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>